Решение основной части ДЗ
TinaevNK/js-part-1 pull request #1
Opened 2022-12-30 20:37 UTC by TinaevNK

# Откуда-Куда/Сколько
---
## Результаты:

1. Сделал какое-то подобие валидации для полей (фокус на пустое поле ставится автоматически), аналогично для второго поля. Решение слабо расширяемое, но тут такой цели и не ставил. По-хорошему прикрутить настоящую валидацию, с блокировкой кнопки сабмита.
![image](https://user-images.githubusercontent.com/90573982/210108375-668afb80-e39b-410b-a96c-e7d0bc79ba68.png)

2. Изменение выходного сообщения при поиске пути. В будущем, я бы добавил какой-нибудь интерактивный лоадер, чтобы пользователь не заскучал.
![image](https://user-images.githubusercontent.com/90573982/210108772-4a05920c-c7df-4b46-a6a1-8aee72558453.png)

3. Тот самый случай, когда лучше полететь на самолёте:)
![image](https://user-images.githubusercontent.com/90573982/210108862-b04b639c-bbf9-4409-9833-1ad44842c3e4.png)

4. Пример успешного поиска пути. 
![image](https://user-images.githubusercontent.com/90573982/210108943-f43c11d7-7e0e-4ed6-b7f6-765d99e9a456.png)

5. Пример невозможности поиска, ввиду отсутствия дорог.
![image](https://user-images.githubusercontent.com/90573982/210109252-591c3a69-7d70-42df-b681-0090d745fe92.png)

6. Пример когда сервер не отвечает (в данном случае я просто вырубил интернет). Да, примитивно, но работает. По хорошему нужно бы считать разные коды ошибок и в их зависимости отдать нужный message. Я сделал всё по дефолту.
![image](https://user-images.githubusercontent.com/90573982/210109414-64cce269-eddc-41fe-af47-bfd94daf0a50.png)
---
## Алгоритм
Тут я шёл по пути наименьшего сопротивления, но из простых запросов он превратился в небольшой костыль. Комментарии в коде я оставлял, думаю будет излишним описывать всё тут. 
Что мне в нём не нравится - так это выбранная структура данных и временная сложность... изначально хотел всё решение завязать на стэке, но не получалось придумать нужную структуру... в итоге сделал в угоду удобства написания кода. Но внутренний алгоритмист хочет всё улучшить)

Что вот хотелось бы сделать лучше (было бы больше времени - думаю попробовал бы), так это оптимизация поиска. Столкнулся с этим, когда во втором поле я ввёл Японию, а в первый Россию. Если бы поиск шёл с обеих сторон - ответ был бы дан быстрее. Но это уже просто хотелки и улучшения, мой вариант всё равно выдаст правильный результат.

Задание понравилось тем, что обычно с dfs и другими алгоритмами обхода проблем не возникало, а на реальной задаче возникли)) В общем очень интересно, но хотел бы посмотреть на "эталонное" решение лекторов) Простое, лаконичное, быстрое. Люблю лучшие практики)

2023-01-07 23:30 UTC, ipetropolsky requested changes

2023-01-07 23:30 UTC, ipetropolsky commented on index.js
> +            throw new Error(borders.message); // попадёт в catch если произошла ошибка
Странно так делать, но ok.

2023-01-07 23:30 UTC, ipetropolsky commented on index.js
> +    try {
Лучше точечно обернуть вызовы, из которых ждёшь ошибок.

2023-01-07 23:30 UTC, ipetropolsky commented on index.js
> +                for (let i = paths.indexOf(path) + 1; i < paths.length; i++) {
Не надо было бы искать `path` каждый раз, если бы в верхнем `for` проходились по индексам и потом `const path = paths[i]`.

2023-01-07 23:30 UTC, ipetropolsky commented on index.js
> +                return 'Очень далеко... давай на самолёте?)';
Кажется это не та функция, в которой надо управлять пользовательским интерфейсом. Лучше сделать ей такой контракт, основываясь на котором внешний код сможет вывести всё что нужно во всех ситуациях.

2023-01-07 23:30 UTC, ipetropolsky commented on index.js
> +        return searchData.resultPaths;
У тебя одна и та же функция возвращает то строку, то набор путей, то ошибку, это не гуд. А то, что по сути является результатом работы функции, записывается в параметр, это тоже не гуд. Из `searchData` ты используешь только `end`, всё остальное — результат работы `search`.

Предлагаю посмотреть на примеры тут: https://github.com/ipetropolsky/js-part-1/pull/3
И сделать более стройный контракт:
* Если ошибка, то `throw` и ловишь снаружи. Если нужны подробности, кладёшь их в объект ошибки.
* Если не ошибка, то возвращаешь всегда объект одного и того же типа со всеми результатами работы.
* Каунтер я бы хранил ближе к запросам, но это уже не так принципиально.

2023-01-09 01:36 UTC, ipetropolsky commented on index.js
> +    if (countries.message) {
Вроде в этом случае должен вылететь эксцепн. 18-я строка. Тут, похоже, ничего не надо делать, если ты всё равно прокидываешь его выше. А ты как-то тестил этот `if`?

2023-01-09 01:36 UTC, ipetropolsky commented on index.js
> +    if (!borders.ok && borders.message) {
Не понял, как может прийти такой `borders`. Ты же если `!response.ok` делаешь `throw response.message`. Ты вообще тестил код? ) Поставь брейкпоинт сюда и сделай ошибку.

2023-01-09 01:36 UTC, ipetropolsky commented on index.js
> +            searchData.requestData.error = true;
В этом случае тебе не нужен объект `searchData`, можно было тоже сделать `throw`, а в вызывающем коде вывести ошибку в `catch`. Но ладно, не принципиально.

2023-01-09 01:36 UTC, ipetropolsky commented on index.js
> +    // или всё же это плохая практика?
Да нормальная. Такие вопросы можно писать комментами к своему PR.

2023-01-09 01:36 UTC, ipetropolsky commented on index.js
> +        output.textContent = 'Упс, произошла ошибка при обращении к серверу, пожалуйста зайдите позже';
А чего прямо в `catch` не вывел? И `return` сразу. А если прошли дальше, значит всё ok.

2023-01-09 01:46 UTC, TinaevNK commented on index.js
> +    if (!borders.ok && borders.message) {
тестил, всё работало, но в конце тестил другое и обратную совместимость не глянул) сейчас поправлю

2023-01-09 01:51 UTC, TinaevNK commented on index.js
> +        output.textContent = 'Упс, произошла ошибка при обращении к серверу, пожалуйста зайдите позже';
![image](https://user-images.githubusercontent.com/90573982/211230102-541610fc-232c-445c-b0e2-430b6f6aac03.png)

2023-01-09 02:02 UTC, TinaevNK commented on index.js
> +    if (countries.message) {
да, действительно
throw на 18й строке пропустит всё это дело
поэтому да, можно убрать вовсе и обработать это в catch функции search

2023-01-13 16:29 UTC, ipetropolsky approved these changes

2023-01-23 15:09 UTC, merged